ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = 1
include $(DEPTH)/config/emptyvars.mk
A11Y_LOG = 1
ACDEFINES = -DX_DISPLAY_MISSING='1' -DHAVE_ARM_SIMD='1' -DHAVE_ARM_NEON='1' -DBUILD_ARM_NEON='1' -DMOZ_PROFILING='1' -DMOZILLA_VERSION='"35.0a1"' -DMOZILLA_VERSION_U='35.0a1' -DMOZILLA_UAVERSION='"35.0"' -DXP_LINUX='1' -DD_INO='d_ino' -DMOZ_DEBUG_SYMBOLS='1' -DSTDC_HEADERS='1' -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE='1' -DHAVE_VISIBILITY_ATTRIBUTE='1' -DHAVE_DIRENT_H='1' -DHAVE_GETOPT_H='1' -DHAVE_SYS_BITYPES_H='1' -DHAVE_MEMORY_H='1' -DHAVE_UNISTD_H='1' -DHAVE_GNU_LIBC_VERSION_H='1' -DHAVE_NL_TYPES_H='1' -DHAVE_MALLOC_H='1' -DHAVE_SYS_QUOTA_H='1' -DHAVE_SYS_SYSMACROS_H='1' -DHAVE_LINUX_QUOTA_H='1' -DHAVE_LINUX_IF_ADDR_H='1' -DHAVE_LINUX_RTNETLINK_H='1' -DHAVE_SYS_TYPES_H='1' -DHAVE_NETINET_IN_H='1' -DHAVE_BYTESWAP_H='1' -DHAVE_SYS_CDEFS_H='1' -DHAVE_DLOPEN='1' -DHAVE_DLADDR='1' -DHAVE_MEMMEM='1' -DNO_X11='1' -D_REENTRANT='1' -DHAVE_STAT64='1' -DHAVE_LSTAT64='1' -DHAVE_TRUNCATE64='1' -DHAVE_LOCALTIME_R='1' -DHAVE_CLOCK_MONOTONIC='1' -DHAVE_RES_NINIT='1' -DHAVE_LANGINFO_CODESET='1' -DVA_COPY='va_copy' -DHAVE_VA_COPY='1' -DHAVE_THREAD_TLS_KEYWORD='1' -DMALLOC_H='<malloc.h>' -DHAVE_STRNDUP='1' -DHAVE_POSIX_MEMALIGN='1' -DHAVE_MEMALIGN='1' -DHAVE_VALLOC='1' -DHAVE_MALLOC_USABLE_SIZE='1' -DHAVE_I18N_LC_MESSAGES='1' -DHAVE_LOCALECONV='1' -DTARGET_XPCOM_ABI='"arm-eabi-gcc3"' -DNS_ATTR_MALLOC='__attribute__((malloc))' -DNS_WARN_UNUSED_RESULT='__attribute__((warn_unused_result))' -DNIGHTLY_BUILD='1' -DMOZ_UPDATE_CHANNEL='nightly' -DEARLY_BETA_OR_EARLIER='1' -DMOZ_XULRUNNER='1' -DMOZ_BUILD_APP='xulrunner' -DMOZ_WIDGET_QT='1' -DQT_NO_KEYWORDS='1' -DMOZ_PDF_PRINTING='1' -DMOZ_ENABLE_QT5FEEDBACK='1' -DMOZ_ENABLE_QT5GEOPOSITION='1' -DMOZ_DISTRIBUTION_ID='"org.mozilla"' -DMOZ_WEBRTC='1' -DMOZ_WEBRTC_ASSERT_ALWAYS='1' -DMOZ_WEBRTC_SIGNALING='1' -DMOZ_PEERCONNECTION='1' -DMOZ_SCTP='1' -DMOZ_SRTP='1' -DMOZ_SAMPLE_TYPE_S16='1' -DMOZ_WEBSPEECH='1' -DMOZ_RAW='1' -DATTRIBUTE_ALIGNED_MAX='64' -DMOZ_WEBM='1' -DMOZ_FFMPEG='1' -DMOZ_FMP4='1' -DMOZ_EME='1' -DMOZ_MEDIA_NAVIGATOR='1' -DMOZ_VPX='1' -DMOZ_VPX_ERROR_CONCEALMENT='1' -DVPX_ARM_ASM='1' -DMOZ_WAVE='1' -DMOZ_TREMOR='1' -DMOZ_OPUS='1' -DMOZ_GSTREAMER='1' -DGST_API_VERSION='"0.10"' -DENABLE_SYSTEM_EXTENSION_DIRS='1' -DMOZ_CRASHREPORTER_ENABLE_PERCENT='100' -DMOZ_USE_NATIVE_POPUP_WINDOWS='1' -DMOZ_FEEDS='1' -DMOZ_URL_CLASSIFIER='1' -DMOZ_GL_PROVIDER='GLContextProviderEGL' -DGL_PROVIDER_EGL='1' -DMOZ_GFX_OPTIMIZE_MOBILE='1' -DMOZ_STACKWALKING='1' -DMOZ_LOGGING='1' -DMOZ_DUMP_PAINTING='1' -DMOZ_MEMORY='1' -DMOZ_MEMORY_DEBUG='1' -DMOZ_MEMORY_LINUX='1' -DJSGC_INCREMENTAL='1' -DJS_GC_ZEAL='1' -DHAVE___CXA_DEMANGLE='1' -DMOZ_DEMANGLE_SYMBOLS='1' -DHAVE__UNWIND_BACKTRACE='1' -DJS_DEFAULT_JITREPORT_GRANULARITY='3' -DMOZ_OMNIJAR='1' -DMOZ_USER_DIR='".mozilla"' -DHAVE_FT_BITMAP_SIZE_Y_PPEM='1' -DHAVE_FT_GLYPHSLOT_EMBOLDEN='1' -DHAVE_FT_LOAD_SFNT_TABLE='1' -DHAVE_FONTCONFIG_FCFREETYPE_H='1' -DMOZ_TREE_PIXMAN='1' -DHAVE_STDINT_H='1' -DHAVE_INTTYPES_H='1' -DMOZ_TREE_CAIRO='1' -DMOZ_ENABLE_SKIA='1' -DUSE_SKIA='1' -DUSE_SKIA_GPU='1' -DMOZ_XUL='1' -DMOZ_PROFILELOCKING='1' -DENABLE_MARIONETTE='1' -DBUILD_CTYPES='1' -DMOZ_SOCIAL='1' -DMOZ_SERVICES_COMMON='1' -DMOZ_SERVICES_CRYPTO='1' -DMOZ_SERVICES_HEALTHREPORT='1' -DMOZ_SERVICES_METRICS='1' -DMOZ_SERVICES_SYNC='1' -DMOZ_MACBUNDLE_ID='org.mozilla.xulrunnerdebug' -DMOZ_B2G_VERSION='"1.0.0"' -DMOZ_B2G_OS_NAME='""' -DMOZ_APP_UA_NAME='""' -DMOZ_APP_UA_VERSION='"35.0a1"' -DFIREFOX_VERSION='35.0a1' -DMOZ_TELEMETRY_DISPLAY_REV='2' -DMOZ_DATA_REPORTING='1' -DMOZ_DLL_SUFFIX='".so"' -DHAVE_POSIX_FADVISE='1' -DHAVE_POSIX_FALLOCATE='1' -DXP_UNIX='1' -DMOZ_REFLOW_PERF='1' -DMOZ_REFLOW_PERF_DSP='1' -DA11Y_LOG='1' -DEXPOSE_INTL_API='1' -DENABLE_INTL_API='1' -DU_STATIC_IMPLEMENTATION='1' -DU_USING_ICU_NAMESPACE='0' -DMOZ_STATIC_JS='1'
AR = ar
ARM_ARCH = 7
AR_DELETE = $(AR) d
AR_EXTRACT = $(AR) x
AR_FLAGS = crs $@
AR_LIST = $(AR) t
AS = $(CC)
ASFLAGS =  -fPIC -Wa,--noexecstack -include $(DEPTH)/mozilla-config.h -DMOZILLA_CLIENT
ASM_SUFFIX = s
AS_DASH_C_FLAG = -c
AUTOCONF = /usr/bin/autoconf
AWK = gawk
BUILD_ARM_NEON = 1
BUILD_CTYPES = 1
CAIRO_FT_CFLAGS = -I/usr/include/freetype2
CC = gcc
CCACHE = no
CC_VERSION = 4.6.4
COMPILE_ENVIRONMENT = 1
CPP = gcc -E
CPU_ARCH = arm
CXX = c++
CXXCPP = c++ -E
CXX_VERSION = 4.6.4
DLL_PREFIX = lib
DLL_SUFFIX = .so
DOXYGEN = :
DSO_LDOPTS = -shared -Wl,-z,defs -Wl,--gc-sections
DSO_PIC_CFLAGS = -fPIC
EARLY_BETA_OR_EARLIER = 1
ENABLE_INTL_API = 1
EXPAND_LIBS_LIST_STYLE = linkerscript
EXPAND_LIBS_ORDER_STYLE = section-ordering-file
FC_FONT_FEATURE = #define CAIRO_HAS_FC_FONT 1
FIREFOX_VERSION = 35.0a1
FT2_CFLAGS = -I/usr/include/freetype2
FT2_LIBS = -lfreetype -lfontconfig
FT_FONT_FEATURE = #define CAIRO_HAS_FT_FONT 1
GCC_USE_GNU_LD = 1
GMAKE = /usr/bin/gmake
GNU_AS = 1
GNU_CC = 1
GNU_CXX = 1
GNU_LD = 1
GRE_MILESTONE = 35.0a1
GSTREAMER_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
GSTREAMER_LIBS = -pthread -lgstapp-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lgstvideo-0.10
GST_API_VERSION = 0.10
HAVE_ARM_NEON = 1
HAVE_ARM_SIMD = 1
HAVE_CLOCK_MONOTONIC = 1
HAVE_INTTYPES_H = 1
HAVE_LINUX_PERF_EVENT_H = 1
HOST_AR = ar
HOST_AR_FLAGS = crs $@
HOST_CC = gcc
HOST_CFLAGS = -O3 -DXP_UNIX -MD -MP -MF $(MDDEPDIR)/$(@F).pp
HOST_CXX = c++
HOST_CXXFLAGS = -O3 -DUSE_ANDROID_OMTC_HACKS=1 -std=gnu++0x -MD -MP -MF $(MDDEPDIR)/$(@F).pp
HOST_MOC = moc
HOST_NSPR_MDCPUCFG = \"md/_linux.cfg\"
HOST_OPTIMIZE_FLAGS = -O3
HOST_OS_ARCH = Linux
HOST_QMAKE = qmake
HOST_RANLIB = ranlib
HOST_RCC = rcc
ICU_LIB_NAMES = icui18n icuuc icudata
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
JAR = :
JARSIGNER = :
JAVA = :
JAVAC = :
JAVAH = :
KEYTOOL = :
LD = ld
LD_PRINT_ICF_SECTIONS = -Wl,--print-icf-sections
LIBS_DESC_SUFFIX = desc
LIBXUL_DIST = /objdir-mer-dbg/dist
LIB_PREFIX = lib
LIB_SUFFIX = a
LN_S = ln -s
MACOS_PRIVATE_FRAMEWORKS_DIR = /System/Library/PrivateFrameworks
MC = mc.exe
MKCSHLIB = $(CC) $(CFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MKSHLIB = $(CXX) $(CXXFLAGS) $(DSO_PIC_CFLAGS) $(DSO_LDOPTS) -Wl,-h,$(DSO_SONAME) -o $@
MKSHLIB_FORCE_ALL = -Wl,--whole-archive
MKSHLIB_UNFORCE_ALL = -Wl,--no-whole-archive
MMX_FLAGS = -mmmx
MOC = moc
MOZILLA_OFFICIAL = 1
MOZILLA_SYMBOLVERSION = 35a1
MOZILLA_VERSION = 35.0a1
MOZ_ALSA = 1
MOZ_ALSA_CFLAGS = -I/usr/include/alsa
MOZ_ALSA_LIBS = -lasound
MOZ_APP_DISPLAYNAME = XULRunner
MOZ_APP_MAXVERSION = 35.0a1
MOZ_APP_NAME = xulrunner
MOZ_APP_VERSION = 35.0a1
MOZ_AUTH_EXTENSION = 1
MOZ_B2G_VERSION = 1.0.0
MOZ_BING_API_CLIENTID = no-bing-api-clientid
MOZ_BING_API_KEY = no-bing-api-key
MOZ_BUILD_APP = xulrunner
MOZ_BUILD_NSPR = 1
MOZ_BUILD_ROOT = /objdir-mer-dbg
MOZ_CAIRO_CFLAGS = -I$(LIBXUL_DIST)/include/cairo
MOZ_CAIRO_OSLIBS = ${CAIRO_FT_OSLIBS}
MOZ_CHILD_PROCESS_BUNDLE = plugin-container.app/Contents/MacOS/
MOZ_CHILD_PROCESS_NAME = plugin-container
MOZ_CHROME_FILE_FORMAT = symlink
MOZ_DATA_REPORTING = 1
MOZ_DEBUG = 1
MOZ_DEBUG_DISABLE_DEFS = -DNDEBUG -DTRIMMED
MOZ_DEBUG_ENABLE_DEFS = -DDEBUG -DTRACING
MOZ_DEBUG_FLAGS = -gdwarf-4
MOZ_DEBUG_SYMBOLS = 1
MOZ_DEMANGLE_SYMBOLS = 1
MOZ_DISTRIBUTION_ID = org.mozilla
MOZ_DOC_INCLUDE_DIRS = ./dist/include ./dist/include/nspr
MOZ_DOC_INPUT_DIRS = ./dist/include ./dist/idl
MOZ_DOC_OUTPUT_DIR = ./dist/docs
MOZ_EME = 1
MOZ_EM_DEBUG = 1
MOZ_ENABLE_CAIRO_FT = 1
MOZ_ENABLE_QT = 1
MOZ_ENABLE_QT5FEEDBACK = 1
MOZ_ENABLE_QT5GEOPOSITION = 1
MOZ_ENABLE_SKIA = 1
MOZ_ENABLE_SKIA_GPU = 1
MOZ_FEEDS = 1
MOZ_FFMPEG = 1
MOZ_FIX_LINK_PATHS = -Wl,-rpath-link,$(LIBXUL_DIST)/bin -Wl,-rpath-link,$(prefix)/lib
MOZ_FMP4 = 1
MOZ_FS_LAYOUT = unix
MOZ_GAMEPAD_BACKEND = stub
MOZ_GFX_OPTIMIZE_MOBILE = 1
MOZ_GLUE_PROGRAM_LDFLAGS = $(MKSHLIB_FORCE_ALL) $(call EXPAND_LIBNAME_PATH,mozglue,$(LIBXUL_DIST)/lib) $(call EXPAND_LIBNAME_PATH,memory,$(LIBXUL_DIST)/lib) $(MKSHLIB_UNFORCE_ALL) -rdynamic
MOZ_GL_DEFAULT_PROVIDER = EGL
MOZ_GL_PROVIDER = EGL
MOZ_GOOGLE_API_KEY = no-google-api-key
MOZ_GSTREAMER = 1
MOZ_ICU_CFLAGS = -I$(topsrcdir)/intl/icu/source/common -I$(topsrcdir)/intl/icu/source/i18n
MOZ_ICU_VERSION = 52
MOZ_JPEG_LIBS = -ljpeg
MOZ_MACBUNDLE_ID = org.mozilla.xulrunnerdebug
MOZ_MACBUNDLE_NAME = XULRunnerDebug.app
MOZ_MEMORY = 1
MOZ_MOZILLA_API_KEY = no-mozilla-api-key
MOZ_NATIVE_JPEG = 1
MOZ_OMNIJAR = 1
MOZ_OPTIMIZE_FLAGS = -freorder-blocks -Os 
MOZ_OPUS = 1
MOZ_PACKAGER_FORMAT = omni
MOZ_PANGO_CFLAGS = -pthread -DMESA_EGL_NO_X11_HEADERS -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng15
MOZ_PANGO_LIBS = -lpangoft2-1.0 -lfreetype -lfontconfig -lpangocairo-1.0 -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0
MOZ_PDF_PRINTING = 1
MOZ_PEERCONNECTION = 1
MOZ_PERMISSIONS = 1
MOZ_PGO_OPTIMIZE_FLAGS = -O3
MOZ_PNG_ARM_NEON = 1
MOZ_PNG_ARM_NEON_CHECK = 1
MOZ_PREF_EXTENSIONS = 1
MOZ_PROFILELOCKING = 1
MOZ_PROFILING = 1
MOZ_PULSEAUDIO = 1
MOZ_PULSEAUDIO_CFLAGS = -D_REENTRANT
MOZ_PULSEAUDIO_LIBS = -lpulse
MOZ_QT_CFLAGS = -I/usr/include/qt5/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtGui/5.2.2/QtGui -I/usr/include/qt5/QtFeedback -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtPositioning -I/usr/include/qt5 -I/usr/include/qt5/QtCore
MOZ_QT_LIBS = -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lQt0Feedback -lQt5Core -lQt5Positioning -lQt5Core
MOZ_RAW = 1
MOZ_REPLACE_MALLOC = 1
MOZ_SAMPLE_TYPE_S16 = 1
MOZ_SCTP = 1
MOZ_SERVICES_COMMON = 1
MOZ_SERVICES_CRYPTO = 1
MOZ_SERVICES_HEALTHREPORT = 1
MOZ_SERVICES_METRICS = 1
MOZ_SERVICES_SYNC = 1
MOZ_SOCIAL = 1
MOZ_SPELLCHECK = 1
MOZ_SRTP = 1
MOZ_STACKWALKING = 1
MOZ_TOOLKIT_SEARCH = 1
MOZ_TREE_CAIRO = 1
MOZ_TREE_PIXMAN = 1
MOZ_TREMOR = 1
MOZ_UI_LOCALE = en-US
MOZ_UNIVERSALCHARDET = 1
MOZ_UPDATE_CHANNEL = nightly
MOZ_UPDATE_PACKAGING = 1
MOZ_URL_CLASSIFIER = 1
MOZ_USE_PTHREADS = 1
MOZ_VPX = 1
MOZ_VPX_ERROR_CONCEALMENT = 1
MOZ_WAVE = 1
MOZ_WEBM = 1
MOZ_WEBRTC = 1
MOZ_WEBRTC_ASSERT_ALWAYS = 1
MOZ_WEBRTC_HAVE_ETHTOOL_SPEED_HI = 1
MOZ_WEBRTC_SIGNALING = 1
MOZ_WEBSPEECH = 1
MOZ_WIDGET_TOOLKIT = qt
MOZ_XUL = 1
MOZ_XULRUNNER = 1
MOZ_ZIPWRITER = 1
NECKO_COOKIES = 1
NECKO_PROTOCOLS = wyciwyg ftp about http res app viewsource file device websocket data
NECKO_WIFI_DBUS = 1
NIGHTLY_BUILD = 1
NSPR_CFLAGS = -I/objdir-mer-dbg/dist/include/nspr
NSPR_LIBS = -L/objdir-mer-dbg/dist/lib -lnspr4 -lplc4 -lplds4
NSPR_PKGCONF_CHECK = nspr
NSS_CFLAGS = -I$(LIBXUL_DIST)/include/nss
NSS_LIBS = -L$(LIBXUL_DIST)/lib -lcrmf -lsmime3 -lssl3 -lnss3 -lnssutil3
OBJCOPY = /usr/bin/objcopy
OBJ_SUFFIX = o
OMNIJAR_NAME = omni.ja
OS_ARCH = Linux
OS_CFLAGS = -Wall -Wpointer-arith -Wdeclaration-after-statement -Werror=return-type -Werror=int-to-pointer-cast -Wtype-limits -Wempty-body -Wsign-compare -Wno-unused -O3 -std=gnu99 -fgnu89-inline -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe
OS_COMPILE_CFLAGS = -include $(DEPTH)/mozilla-config.h -DMOZILLA_CLIENT -MD -MP -MF $(MDDEPDIR)/$(@F).pp
OS_COMPILE_CXXFLAGS = -DMOZILLA_CLIENT -include $(DEPTH)/mozilla-config.h -MD -MP -MF $(MDDEPDIR)/$(@F).pp
OS_CXXFLAGS = -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Werror=int-to-pointer-cast -Werror=type-limits -Wempty-body -Wsign-compare -Wno-invalid-offsetof -O3 -DUSE_ANDROID_OMTC_HACKS=1 -fno-exceptions -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe
OS_LDFLAGS = -lpthread  -Wl,-z,noexecstack -Wl,-z,text -Wl,--build-id -Wl,--icf=safe
OS_LIBS = -ldl 
OS_RELEASE = 3.13-1-amd64
OS_TARGET = Linux
OS_TEST = armv7l
PDF_SURFACE_FEATURE = #define CAIRO_HAS_PDF_SURFACE 1
PERL = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
PROFILE_GEN_CFLAGS = -fprofile-generate
PROFILE_GEN_LDFLAGS = -fprofile-generate
PROFILE_USE_CFLAGS = -fprofile-use -fprofile-correction -Wcoverage-mismatch
PROFILE_USE_LDFLAGS = -fprofile-use
PYTHON = /objdir-mer-dbg/_virtualenv/bin/python
PYTHON_SITE_PACKAGES = /objdir-mer-dbg/_virtualenv/lib/python2.7/site-packages
QT_SURFACE_FEATURE = #define CAIRO_HAS_QT_SURFACE 1
RANLIB = ranlib
RCC = rcc
REALTIME_LIBS = -lrt
RPMBUILD = /usr/bin/rpmbuild
SHELL = /bin/sh
SSE2_FLAGS = -msse2
SSE_FLAGS = -msse
STL_FLAGS = -I$(DIST)/stl_wrappers
STRIP = strip
STRIP_FLAGS = --strip-debug
TAR = tar
TARGET_CPU = armv7l
TARGET_MD_ARCH = unix
TARGET_NSPR_MDCPUCFG = \"md/_linux.cfg\"
TARGET_OS = linux-gnueabihf
TARGET_VENDOR = unknown
TARGET_XPCOM_ABI = arm-eabi-gcc3
TEE_SURFACE_FEATURE = #define CAIRO_HAS_TEE_SURFACE 1
TK_CFLAGS = $(MOZ_QT_CFLAGS)
TK_LIBS = $(MOZ_QT_LIBS)
UNZIP = /usr/bin/unzip
USE_DEPENDENT_LIBS = 1
VISIBILITY_FLAGS = -I$(DIST)/system_wrappers -include $(MOZILLA_DIR)/config/gcc_hidden_dso_handle.h
VPX_ARM_ASM = 1
VPX_AS = $(CC)
VPX_ASFLAGS = -march=armv7-a -mfpu=neon
VPX_ASM_SUFFIX = s
VPX_AS_CONVERSION = $(PERL) $(topsrcdir)/media/libvpx/build/make/ads2gas.pl
VPX_DASH_C_FLAG = -c
WINDRES = :
WRAP_STL_INCLUDES = 1
WRAP_SYSTEM_INCLUDES = 1
XARGS = /usr/bin/xargs
XULRUNNER_STUB_NAME = xulrunner-stub
ZIP = /usr/bin/zip
_FONTCONFIG_LIBS = -lfontconfig
_PANGOCHK_CFLAGS = -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
_PANGOCHK_LIBS = -lpango-1.0 -lgobject-2.0 -lglib-2.0
_QT5FEEDBACK_CFLAGS = -I/usr/include/qt5/QtFeedback -I/usr/include/qt5 -I/usr/include/qt5/QtCore
_QT5FEEDBACK_LIBS = -lQt0Feedback -lQt5Core
_QT5GEOPOSITION_CFLAGS = -I/usr/include/qt5/QtPositioning -I/usr/include/qt5 -I/usr/include/qt5/QtCore
_QT5GEOPOSITION_LIBS = -lQt5Positioning -lQt5Core
ac_configure_args =  --prefix=/usr --with-system-jpeg --with-gl-provider=EGL --enable-application=xulrunner --enable-update-channel=nightly --enable-update-packaging --enable-tests --enable-default-toolkit=cairo-qt --enable-optimize --enable-mobile-optimize --enable-profile-guided-optimization --enable-debug-symbols=-gdwarf-4 --enable-cpp-rtti --enable-skia --disable-dbus --disable-updater --disable-gamepad --disable-printing --enable-webrtc --enable-profiling --enable-gstreamer --disable-dbus --disable-necko-wifi --disable-accessibility --without-x --enable-debug --enable-logging --disable-optimize --without-x --disable-tests --disable-accessibility --disable-dbus --disable-necko-wifi
bindir = ${exec_prefix}/bin
build = armv7l-unknown-linux-gnueabihf
build_alias = armv7l-unknown-linux-gnueabihf
build_cpu = armv7l
build_os = linux-gnueabihf
build_vendor = unknown
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = armv7l-unknown-linux-gnueabihf
host_alias = armv7l-unknown-linux-gnueabihf
host_cpu = armv7l
host_os = linux-gnueabihf
host_vendor = unknown
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = armv7l-unknown-linux-gnueabihf
target_alias = armv7l-unknown-linux-gnueabihf
target_cpu = armv7l
target_os = linux-gnueabihf
target_vendor = unknown
top_srcdir = /mozilla-central
include $(topsrcdir)/config/baseconfig.mk
endif
